use _MSC_VER instead of WIN32 for Visual Studio
fixes the following when using MinGW-w64
```
graph.c:276:10: warning: 'Agdirected' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 Agdesc_t Agdirected = { 1, 0, 0, 1 };
          ^
graph.c:277:10: warning: 'Agstrictdirected' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 Agdesc_t Agstrictdirected = { 1, 1, 0, 1 };
          ^
graph.c:278:10: warning: 'Agundirected' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 Agdesc_t Agundirected = { 0, 0, 0, 1 };
          ^
graph.c:279:10: warning: 'Agstrictundirected' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 Agdesc_t Agstrictundirected = { 0, 1, 0, 1 };
          ^
graph.c:281:10: warning: 'AgDefaultDisc' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 Agdisc_t AgDefaultDisc = { &AgMemDisc, &AgIdDisc, &AgIoDisc };
          ^
graph.c:281:1: error: initializer element is not constant
 Agdisc_t AgDefaultDisc = { &AgMemDisc, &AgIdDisc, &AgIoDisc };
 ^
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.mem')
graph.c:281:1: error: initializer element is not constant
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.id')
graph.c:281:1: error: initializer element is not constant
graph.c:281:1: error: (near initialization for 'AgDefaultDisc.io')
```